name: Test and Tag

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stable'

env:
  BTP_URL: https://api.cf.us10.hana.ondemand.com
  CF_ORG: en06-dev-aws
  CF_SPACE: dev

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@27c0c9dcab679d7250dbab91227c85b49ffa5e0f # v3.0.0
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            cef670b6-a372-4ee7-8d86-b1a000f56a3c > CF_USERNAME
            6db2a260-106e-4a5a-b612-b1a000f5a374 > CF_PASSWORD
      
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      
      - name: Deploy to BTP
        uses: ./
        with:
          api: ${{ env.BTP_URL }}
          username: ${{ env.CF_USERNAME }}
          password: ${{ env.CF_PASSWORD }}
          org: ${{ env.CF_ORG }}
          space: ${{ env.CF_SPACE }}
          manifest: 'manifest.yml'
      
      - name: Cleanup PR
        uses: ./
        with:
          api: ${{ env.BTP_URL }}
          username: ${{ env.CF_USERNAME }}
          password: ${{ env.CF_PASSWORD }}
          org: ${{ env.CF_ORG }}
          space: ${{ env.CF_SPACE }}
          command: cf delete ghac-btp-deploy-pr -f -r
          
      - name: Create tag
        if: github.event_name != 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            } catch (err) {
              console.log(err)

              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            }